[package]
name = "flow_features"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.40"
clap = { version = "3.1.8", features = ["derive"] }
env_logger = "0.8.3"
jsonl = "4.0.1"
lazy_static = "1.4.0"
log = { version = "0.4", features = ["release_max_level_info"] }
regex = "1.5.4"
iris-core = { path = "../../core" }
iris-compiler = { path = "../../compiler" }
iris-datatypes = { path = "../../datatypes" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
smartcore = { git = "https://github.com/smartcorelib/smartcore", features = ["datasets"] }
bincode = "1.3.3"
csv = "1.2.1"
array-init = "2.0"
chrono = "0.4"
parking_lot = "0.12.4"
indexmap = "2.11.1"

hdrhistogram = "7"
once_cell = "1"
plotters = "0.3"